# Simplified Windows MSVC build that produces PDB-friendly artifacts for Ghidra.
name: Windows CI (MSVC minimal)

on:
  push:
    branches: [ master, 'release/**' ]
    paths-ignore:
      - 'compile_commands/**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    name: MSVC Debug (core + empty)

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: MSVC dev command prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure (VS2022, core + empty only)
        shell: pwsh
        run: >
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64
          -DCMAKE_BUILD_TYPE=Debug
          -DWITH_BOOST=OFF
          -DSOCI_TESTS=OFF
          -DSOCI_SHARED=ON
          -DSOCI_STATIC=ON
          -DSOCI_EMPTY=ON
          -DSOCI_SQLITE3=OFF
          -DSOCI_DB2=OFF
          -DSOCI_FIREBIRD=OFF
          -DSOCI_ORACLE=OFF
          -DSOCI_ODBC=OFF
          -DSOCI_POSTGRESQL=OFF
          -DSOCI_MYSQL=OFF

      - name: Build
        shell: pwsh
        run: cmake --build build --config Debug -j2

      - name: Package (full + PDBs)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path out\full\bin,out\full\lib,out\full\include | Out-Null
          if (Test-Path include) { Copy-Item -Recurse -Force include\* out\full\include\ }
          Get-ChildItem -Recurse build -Include *.dll,*.exe | Copy-Item -Destination out\full\bin -Force
          Get-ChildItem -Recurse build -Include *.lib | Where-Object { $_.Name -like "soci*.lib" } | Copy-Item -Destination out\full\lib -Force
          # symbols (PDB)
          New-Item -ItemType Directory -Force -Path out\symbols | Out-Null
          Get-ChildItem -Recurse build -Include *.pdb | Copy-Item -Destination out\symbols -Force

      - name: Upload artifact (full + pdb)
        uses: actions/upload-artifact@v4
        with:
          name: ghidra-full-windows-msvc-Debug
          path: |
            out/full/**
            out/symbols/**
          if-no-files-found: warn
          retention-days: 30
